upstream:
  default:
    - 1.1.1.1
    - 8.8.8.8
    - 4.2.2.4
# blocking:
#   blackLists:
#     ads:
#       - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
#   clientGroupsBlock:
#     default:
#       - ads
customDNS:
  customTTL: 6h
  filterUnmappedTypes: true
  rewrite:
    lan: home
    home.arpa: home
  mapping:
    cloud.home: 192.168.1.2
    app.home: 192.168.1.2
    dev.home: 192.168.1.3
    velop.home: 192.168.1.1
    router.home: 192.168.0.1
prometheus:
  enable: false
queryLog:
  type: console
log:
  level: info
  privacy: true
ports:
  dns: 53
  http: 4000